### ISSUE TITLE
NOT an existing issue - only a question or a feature request in a way...

### ISSUE THREAD

**Issue by prl77** [legege/searchwp#104]
Hey man, just a quick question for ya... Any chance of making such an extension for Chrome? I switched to that browser recently and really miss this extension. Or do you know of any that exist already? I couldn't find any.

Thanks,
Peter

**Comment by Ede123** [comment]
* For the highlighting part there are some alternatives, see [this link](http://www.makeuseof.com/tag/4-browser-extensions-for-searching-multiple-words-on-a-webpage-chrome-firefox/) for a selection.
* For the jump-to-word buttons I don't know of anything comparable.

I can't speak for the other devs but I assume it's unlikely anyone will write an extension for Chrome. Personally I did not even use Chrome once and I don't plan to do anytime soon, let alone extension development.

If you find an alternative yourself feel free to report it here.
