### ISSUE TITLE
Enable empty searches

### ISSUE THREAD

**Issue by CamilleBouliere** [legege/searchwp#108]
When I use "WP_Query" having no "s" argument or an empty one or an '%' returns results.

When I use "SWP_Query" nothing is returned.

I can't find any argument to enable empty searches or even wildcards. Could you help me ? Thanks.

**Comment by Ede123** [comment]
I assume this bug is related to the Wordpress SearchWP plugin?

This is the repository for the SearchWP add-on for Firefox, which is completely unrelated...
