### ISSUE TITLE
FF 48 not working

### ISSUE THREAD

**Issue by alx37** [legege/searchwp#109]
Not working in Firefox 48.
Button/Controls work but with no effect.

**Comment by Ede123** [comment]
Could you give some more details on your system and on what you're trying to do?

Latest stable version works fine for me on Firefox 48.0 on Windows 10

**Comment by alx37** [comment]
Firefox 48.0 64Bit or 49b3 x86 Win10, same problem, even if all other addons are deactivated.
reinstall of addon did not solve.
Highlight button is working but no text on the website is highlighted.
Quicksearch-dropdown menu is created but when selecting one it does not lead to a search result.
Basically all controls and integrations into search bar work but functions on the actual webpage have no effect.
I've been using SearchWP for a couple of years now...
I can perform any tests if you like.

**Comment by Ede123** [comment]
First of all open your browser console and check if there are any errors logged that might help revealing the issue. This is best done *directly after restarting* the browser (some errors are logged at startup), preferably with a *clean profile*. Afterwards do some typical tasks (searching something, clicking the highlighter button or a search token) and check if further errors were logged to the console.

If in doubt on what might be useful simply copy&paste the whole console content.

**Comment by alx37** [comment]
I'm trying to pin down the problem.
It does not happen on a clean profile.
I did a full backup with FEBE.
When restoring in a new profile I can reinstall all addons with no problem whatsoever.
Problem starts when restoring the settings via FEBE.
I'll do a comparison between clean new profile settings and the backup and hopefully find the issue...
I'll also take a look into the console.

**Comment by alx37** [comment]
Pos: I have a new full working profile which is way small than before.
Neg: Time consumation.

But I found the reason: browser.tabs.remote.force-enable set to true
So for all having trouble remove multi thread support!

**Comment by Ede123** [comment]
Great, good to know what the problem was...

You'd probably love to hear that the next version will support e10s. In fact the code currently in this repository should work with multi-threaded Firefox already.

If you like to experiment feel free to check out the attached development version (needs to be renamed to .xpi; note that you won't be able to install it in a release version of Firefox though, since the XPI it's not signed).
[SearchWP_dev.zip](https://github.com/legege/searchwp/files/418984/SearchWP_dev.zip)
