### ISSUE TITLE
Highlighting in large document where html file is large as 25 mb 

### ISSUE THREAD

**Issue by luckyprime** [legege/searchwp#110]
Is there is any way out to apply searchwp highlighter on certain mb of file not all at once as this do not work on large files.

Further i have seen such tools on internet which work on text format with a optional loading of text restricted by MBs.

This will help to handle tool to slightly highlight and search instead of crashing. 

Can any one help on the issue as I am not a developer but I can suggest the problem I have faced.

Thanks in advance for providing such a great tool.

**Comment by Ede123** [comment]
Check out the [hidden setting](https://github.com/legege/searchwp/wiki/Documentation#hidden-settings) `extensions.searchwp.highlight.maxColorizedHighlights`.

It should solve your issue...

**Comment by luckyprime** [comment]
Thank you for the answer.
I m really thankful you for the quick response but I would further like to
ask one more thing that can I save the html file containg highlight.

Even I appreciate if I can highlight one word at a time but need two things

a) how to save highlighted document preferably html file.

b) how can I assign different color to each search term I have searched or
I want to say color customization of searched word.

Thankyou for your help and response. Waiting for your suggestions.

**Comment by Ede123** [comment]
a) If Firefox's native highlighting is used, it unfortunately can't be saved.<br>However if SearchWP's highlighter is used the highlights will be saved by default. You might have to adjust CSS styles in the saved document, e.g. by adding the following to the `<head>` of the saved HTML document:

``` HTML
<style>
.searchwp-term {
  color: black;
}

.searchwp-term[highlight="term-1"] {
  background-color: #fbed73;
}

.searchwp-term[highlight="term-2"] {
  background-color: #ffb18c;
}

.searchwp-term[highlight="term-3"] {
  background-color: #ffd281;
}

.searchwp-term[highlight="term-4"] {
  background-color: #c3f991;
}

.searchwp-term[highlight="term-5"] {
  background-color: #e9b8ff;
}
</style>
```

b) Adjust the color values above. If it should be the new default, see the [FAQ](https://github.com/legege/searchwp/wiki/FAQ#how-do-i-change-highlighting-colors)
